### ISSUE TITLE
Have max-width property on main config

### ISSUE THREAD

**Issue by skitterm** [DoclerLabs/Protip#13]
It'd be nice if you could set a max-width for all of your tooltips at config time instead of having to specify each one individually.

**Comment by wintercounter** [comment]
True, making all default options configurable easily soon. I don't know how I forgot such thing. Thanks for the tip.

**Comment by wintercounter** [comment]
Now you can set every default values at initialization. Example:
```javascript
$.protip({
    defaults: {
        width: 200,
        position: 'bottom'
    }
})
```
See docs for further info. Please note this is a breaking change as i had to remove `animation`, `scheme`, `size` and `skin` properties from the config object as from now on these should be set through the `defaults` property also.

**Comment by pappfer** [comment]
FYI: the CDN version seems to be older, it doesn't support this functionality yet.
`//cdn.rawgit.com/DoclerLabs/Protip/master/protip.min.js`

**Comment by wintercounter** [comment]
Thanks for the notice. I've change to `min.gitcdn.xyz` every assets. Rawgit caches once only...

**Comment by wintercounter** [comment]
Weird, seems like they having an issue serving a CSS file. I've opened an issue for them and I'll search for another solution if it won't be handled in 1-2 hours.
