### ISSUE TITLE
Make selector's text as default title

### ISSUE THREAD

**Issue by pappfer** [DoclerLabs/Protip#16]
I think it makes sense to have the selector's text as the default one for the tooltip. Bootstrap does this, too.

Also, what does `$(this)` refer to? I tried to make the element's text the default title (see code below), but this solution didn't work.

```javascript
$.protip({
    selector: '.jstree-anchor',
    defaults: {
        title: $(this).text()
    }
});
```

**Comment by wintercounter** [comment]
There is no closure, `this` will refer your own scope. I understand what you want to achieve but I don't know what would be the use case for this. Can you explain your why you want the tooltip have the same content as the element you have the tooltip on?

**Comment by pappfer** [comment]
For example when the text won't fit the container. See screenshot.
![protip](https://cloud.githubusercontent.com/assets/738623/11685661/ff0dd1d0-9e7a-11e5-88d5-8e87583cfc9a.png)

**Comment by wintercounter** [comment]
Looks reasonable. I'll do it later this day or tomorrow. Also please note that I'm going to use `innerHTML` instead of `textContent`.

BTW: Udv :)

**Comment by wintercounter** [comment]
It's done. It took faster than i tought :) Now you may use the `:this` operator in the title attribute.

```javascript
$.protip({
    selector: '.jstree-anchor',
    defaults: {
        title: ':this'
    }
});
```
