### ISSUE TITLE
proper npm usage?

### ISSUE THREAD

**Issue by aft-luke** [DoclerLabs/Protip#18]
Hey there, 

After evaluating 5 serious contenders for a good tooltip, I settled on Protip. I'm trying to use NPM to fold the library into my app code, but I keep getting 'Error: Cannot find module 'browserify-shim' from '{...removed...}/node_modules/protip'. I see you have the shim listed as a dev dependency, but I couldn't get it to work until I declared my own `package.json` to use the shim as a dev dependency as well. Thoughts?

**Comment by wintercounter** [comment]
First: Sorry for the inconvenience and thanks for the report.
Second: I'll update this on the weekend. Until I would suggest you to require the minified js and not the module itself so you won't even need to install that package.

**Comment by wintercounter** [comment]
Sorry again for late, life happened :) We tried to reproduce the issue, but we couldn't, we're using Protip on several pages simply with require but everything works fine. Maybe something got messed up with your node_modules. Anyway I've updated the dependencies to the latest, I hope it'll help to you. Closing ticket now.
