### ISSUE TITLE
destroy / reinitialize

### ISSUE THREAD

**Issue by netopolit** [DoclerLabs/Protip#25]
Is there a way to reinitialize the plugin after loading content with ajax?

Thank you

**Comment by netopolit** [comment]
I am replacing parts of the page via ajax depending on user interaction. 

In this particular case I'm building a telecom website/web app. On one page user can combine certain services. Depending on which services user choose a part of the page should be dynamically rerendered to mach the users criteria. I'd like to show tooltips on that page fragment loaded via ajax.

**Comment by wintercounter** [comment]
It should automatically listen to DOM changes and find/initialize tooltips on the new nodes. Have you disabled observer at pligin initialization (`observer: false`)?

**Comment by netopolit** [comment]
I see it now, thanks. I haven't disabled the observer. Setting childList to true on MutationObserverInit object makes it work for me.

Thanks.
