### ISSUE TITLE
Change title content dynamically

### ISSUE THREAD

**Issue by SebastianPelaez** [DoclerLabs/Protip#26]
Hello i have this situation, i have a text area with maxlength = "200" so, what i need is change the title of the protip when the textarea key up, and show; Max lenght 200, 199, 198... etc, i tried changing data-pt-title attribute and i tried removing and adding the class, but nothing works, can you help? sorry for my bad english. i mean something like in jqueryUI.. : $( ".selector" ).tooltip( "option", "content", "Awesome title!" );

**Comment by wintercounter** [comment]
Solution 1: Try using observer. This will listen to changes in your
attributes.
```
<textarea class="protip" data-pt-observer="true" data-pt-title="Max length
is 200" maxlength="200"></textarea>

var el = $('textarea');
el.attr('data-pt-title', 'Max length is ' + el.attr('maxlength'))
```

Solution 2: Update manually.
```
<textarea maxlength="200"></textarea>

var el = $('textarea');
el.on('change', function() {
    el.protipSet{
        title: 'Max length is ' + el.attr('maxlength')
    }
})
```

**Comment by wintercounter** [comment]
Solution 1: Try using observer. This will listen to changes in your
attributes.
```
<textarea class="protip" data-pt-observer="true" data-pt-title="Max length
is 200" maxlength="200"></textarea>

var el = $('textarea');
el.attr('data-pt-title', 'Max length is ' + el.attr('maxlength'))
```

Solution 2: Update manually.
```
<textarea maxlength="200"></textarea>

var el = $('textarea');
el.on('change', function() {
    el.protipSet{
        title: 'Max length is ' + el.attr('maxlength')
    }
})
```

**Comment by SebastianPelaez** [comment]
Thank you so much, that's worked. I have another question, when we used ASP.Net and we defined the compatibility in the webconfig, if we choose a version of internet explorer that is diferent than version that we have, example: <add key="CompatibilityMode" value="IE=10" />, the browser run in this document mode as default, in this specific case the tooltips doesn't work. We need to use the compatibility to give support to old pages, but in the new ones we love use tooltips, but this doesn't work just for internet explorer. can you help me with that? 

![iedocumentmode](https://cloud.githubusercontent.com/assets/24530345/21146241/f4b6666c-c11e-11e6-966f-1d97e72b4ed3.jpg)

**Comment by wintercounter** [comment]
For IE10 and below you need to use a MutationObserver polyfill. It's in the README:

"MutationObserver (IE8-10 Support)

Internet Explorer supports Mutation Observers only from version 11. In case you need IE8-10 support you need to include a Mutation Observer Polyfill. Simply include this script before Protip is loaded https://github.com/megawac/MutationObserver.js"
