### ISSUE TITLE
Show one tooltip at a time

### ISSUE THREAD

**Issue by kuzvac** [DoclerLabs/Protip#6]
Hi i found your awesome plugin, and try to use in my project. For example: i have some links with tooltip on page, tooltip triggering by click. If I click on the first link, and then on the second, both tooltips are visible. 
How i can show only one tooltip at a time? Custom show event or is there a better solution?

**Comment by wintercounter** [comment]
Can you show me a code example please how you're using.

**Comment by wintercounter** [comment]
I'm closing this ticket now, feel free to reopen if needed.

**Comment by kuzvac** [comment]
Hah, you awesome! At the time I did fiddle with the example, you fix it :D 
Thank you!
