### ISSUE TITLE
Is the gravity data-pt-gravity attribute working?

### ISSUE THREAD

**Issue by egosbry** [DoclerLabs/Protip#7]
```HTML
<a href="#bar" class="protip" data-pt-gravity="left" data-pt-title="You must be at least 18!">
    Go to the bar!
</a>
```

This config will still let the tooltip appear on the right side. Please advice...

**Comment by wintercounter** [comment]
It was a bug when min-width calculation applied. Now it should be fixed, thanks for the report.

**Comment by egosbry** [comment]
Thanks for quick fix.

But the tooltip is now gone wild when it has a lot of content for about more than 7 paragraph.

**Comment by wintercounter** [comment]
Do you have any public link to show the issue?

**Comment by egosbry** [comment]
Nope. Can you try to re-produce on one of your demos? Just insert huge text and apply the controlled gravity e.g. bottom-left; bottom-right

**Comment by wintercounter** [comment]
A screenshot maybe? Anyway, I've tried to guess your issue and added a "fix", would you please try again?

**Comment by egosbry** [comment]
much better now but it overflows even it still have available space on the right side

![screen shot 2015-10-01 at 6 27 15 pm](https://cloud.githubusercontent.com/assets/12706751/10218550/3149830c-686a-11e5-8f09-410516d959a0.png)

**Comment by wintercounter** [comment]
I've played with lots of contents now, but couldn't find any issues so far. It's also hard to see anything from the screenshot. Where is the source element on the screenshot, and what is the tooltip position?

**Comment by egosbry** [comment]
can you resize your browser in any sizes and see if occurs

**Comment by wintercounter** [comment]
I've tried, but no success. Still trying :)

**Comment by wintercounter** [comment]
TeamViewer maybe if it's not confidential?

**Comment by wintercounter** [comment]
Or please send me the exact HTML you're using. Maybe an issue with a parameter...

**Comment by egosbry** [comment]
how about adding attribute data-pt-width="700"

**Comment by wintercounter** [comment]
It's working fine form me with both `700` and `700!`

**Comment by wintercounter** [comment]
https://gitter.im/DoclerLabs/Protip?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Maybe we would find the issue in chat.
