### ISSUE TITLE
Add info to protiphide event, that it calls from Onresize event

### ISSUE THREAD

**Issue by kuzvac** [DoclerLabs/Protip#9]
Hello again :) 
Can you please add information to the "protiphide" event to understand that it is called from "Onresize" event?
I need to know that protiphide event was launched from resizing or other events.
I made "dirty hack", but don't know, how doing it properly :)

**Comment by wintercounter** [comment]
I've added a fix, now it shouldn't run, but no time to test it, so please do it for me :D

**Comment by kuzvac** [comment]
Yes, that's what was needed. You're best! :) thanks.
